name: reusable workflow

on: 
  workflow_call:
    inputs:
      demo:
        required: false
        type: string
env:
  demo: '${{ inputs.demo }}'
jobs:
  test-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: print
      id: echo
      run: |
        echo "this workflow is reusable workflow. It triggererd when ${{ env.demo }}"
