name: pull request

on: 
  pull_request:
    branches:
      - "main"

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: print
      id: echo
      run: |
        echo "this workflow trigered when you raised a PR into a main branch"

    - name: reusable
      uses: ./.github/actions
      with:
        event: ${{ github.event_name }}        
