name: workflow run

on: 
  workflow_run:
    workflows: ["workflow dispatch"]
    types:
      - completed

jobs:
  test-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: print
      id: echo
      run: |
        echo "this workflow trigered when the dependent workflow workflow dispatch"
    
    - name: reusable
      uses: ./.github/actions
      with:
        event: ${{ github.event_name }}
