name: workflow dispatch

on: workflow_dispatch

jobs:
  test-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: print
      id: echo
      run: |
        echo "this workflow trigered when you run this manually"
        
    - name: reusable
      uses: ./.github/actions
      with:
        event: ${{ github.event_name }}